# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    
  admin:
    image: adminer
    ports:
      - "8080:8080"

  backend:
    build: 
      context: ./server/.
    container_name: backend
    ports:
      - "3000:3000"

  front:
    build:
      context: ./front/.
    container_name: front
    ports:
      - "9000:9000"

volumes:
  mysql: